### Login
POST http://localhost:8000/layanan/login
Content-Type: application/json

{
    "userName": "kotakelektronik@gmail.com",
    "password": "12345"
}

### Login
POST http://api.kemkes.go.id/faskes/login
Content-Type: application/json

{
    "userName": "kotakelektronik@gmail.com",
    "password": "p5fuNGds"
}

### INM RS
GET http://localhost:8000/layanan/kkt-rs?kode=1102016&tahun=2022&bulan=10&page=1&limit=10

### INM RS
GET http://localhost:8000/layanan/kpapd-rs?kode=1102016&tahun=2022&bulan=10&page=1&limit=10

### INM RS
GET http://localhost:8000/layanan/kwvt-rs?kode=1102016&tahun=2022&bulan=10&page=1&limit=10

### INM RS
GET http://localhost:8000/layanan/kpfnt-rs?kode=1102016&tahun=2022&page=1&limit=10

### INM RS
GET http://localhost:8000/layanan/kwt-rs?kode=1102016&tahun=2022&page=1&limit=10

### sirs tahunan
GET http://localhost:8000/layanan/sirs-dua?kode=1102016&tahun=2022&page=1&limit=10

### sirs bulanan
GET http://localhost:8000/layanan/sirs-satu?kode=1102016&bulan=5&tahun=2023&page=1&limit=10

